name: Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3
    - name: Install dependencies
      run: |
        python -m pip install -U pip==24.1.2
        python -m pip install pdm==2.16.1
        pdm install
    - name: Lint and format
      run: |
        pdm run ruff check .
        pdm run ruff format --check .
        pdm run isort --check-only .
        pdm run mypy .
    - name: Test
      run: |
        pdm run pytest tests
